### ISSUE TITLE
minbox's result is wrong?

### ISSUE THREAD

**Issue by yzl96** [Vandaci/Lidar_Perception_Apollo#1]
Hi, thanks for your work, when I run your code, I find some wrong result in minbox.
![image](https://user-images.githubusercontent.com/31734981/67254157-21332e80-f4ae-11e9-86fe-50c10afc1729.png)

![image](https://user-images.githubusercontent.com/31734981/67254193-59d30800-f4ae-11e9-90da-195738947025.png)

I can detection the object, but in last step : minbox, the angle seems wrong for lots of objects.

**Comment by yzl96** [comment]
just use cv2.minAreaRect(points)， the result is ok.
![image](https://user-images.githubusercontent.com/31734981/67255720-141a3d80-f4b6-11e9-9727-cea51c094c3d.png)

**Comment by Vandaci** [comment]
I have debugged, it should be ok, thank you for trying

**Comment by Vandaci** [comment]
This is not my final version, due to code hosting issues, I may not have uploaded

**Comment by zqzqz** [comment]
@Vandaci  These are problems in minbox calculation. I test your code using dataset http://cadcd.uwaterloo.ca/ but following errors occur.

```
Traceback (most recent call last):
  File "test_weather.py", line 72, in <module>
    objects = process(file_path)
  File "test_weather.py", line 58, in process
    box = mbox.MinBox(points)
  File "/z/qzzhang/Lidar_Perception_Apollo/src/minbox.py", line 19, in __init__
    self.GetValidBon()  # 获取有效边
  File "/z/qzzhang/Lidar_Perception_Apollo/src/minbox.py", line 50, in GetValidBon
    max_idx = np.where(self.valid_bon == max_point_idx)[0][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

I attached the corresponding pcd file. 
[pcd.zip](https://github.com/Vandaci/Lidar_Perception_Apollo/files/4718358/pcd.zip)

Currently, it seems opencv API is a good alternative. Thanks for your work though.
